name: Release

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17.0.7'
          distribution: graalvm
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

#      - name: Update version
#        run: mvn versions:set -DnewVersion=${GITHUB_REF#refs/tags/}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build native image
        run: native-image --no-server -jar target/jeditor-0.0.1-jar-with-dependencies.jar

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            target/jeditor-0.0.1-jar-with-dependencies.exe
